/* Process data layout. Generated by EC-Engineer V2.0.0
 * DO NOT EDIT!
 * 
 * Sample Code:
 * 
 * // Getting the process image
 * EC_T_BYTE* pbyPDIn = ecatGetProcessImageInputPtr();
 * EC_T_BYTE* pbyPDOut = ecatGetProcessImageOutputPtr();
 * 
 * // Accessing the complete PD layout
 * T_PDLAYOUT_IN* pPDIn = (T_PDLAYOUT_IN*)pbyPDIn;
 * T_PDLAYOUT_OUT* pPDOut = (T_PDLAYOUT_OUT*)pbyPDOut;
 * 
 * // Accessing a single slave of the PD layout
 * T_PDLAYOUT_IN_SLAVE_1001* pSlaveIn = (T_PDLAYOUT_IN_SLAVE_1001*)(pbyPDIn + PDLAYOUT_IN_OFFSET_SLAVE_1001);
 * T_PDLAYOUT_OUT_SLAVE_1001* pSlaveOut = (T_PDLAYOUT_OUT_SLAVE_1001*)(pbyPDOut + PDLAYOUT_OUT_OFFSET_SLAVE_1001);
 */

#ifndef PDLAYOUT_H
#define PDLAYOUT_H

#include "EcOs.h"

/*-INPUT SLAVES--------------------------------------------------------------*/

#include EC_PACKED_INCLUDESTART(1)
#define PDLAYOUT_IN_OFFSET_SLAVE_1001 0
typedef struct _T_PDLAYOUT_IN_SLAVE_1001
{
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Actual_Position;                // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Position (Offset: 0.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Actual_Velocity;                // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Velocity (Offset: 4.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Absolute_Position;              // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Absolute Position (Offset: 8.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Rotor_Absolute_Position;        // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Rotor Absolute Position (Offset: 12.0, Size: 4.0, Datatype: DINT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Inputs_Actual_Torque;                   // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Torque (Offset: 16.0, Size: 2.0, Datatype: INT)
  EC_T_WORD   wModule_1_csv_csp__axis_Inputs_Status_Word;                      // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Status Word (Offset: 18.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wModule_1_csv_csp__axis_Inputs_Error_Code;                       // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Error Code (Offset: 20.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Inputs_Mode_of_Operation_Display;       // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Mode of Operation Display (Offset: 22.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Inputs_Torque_Sensor;                   // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Torque Sensor (Offset: 24.0, Size: 2.0, Datatype: INT)
} EC_PACKED(1) T_PDLAYOUT_IN_SLAVE_1001;
#include EC_PACKED_INCLUDESTOP

#include EC_PACKED_INCLUDESTART(1)
#define PDLAYOUT_IN_OFFSET_SLAVE_1002 26
typedef struct _T_PDLAYOUT_IN_SLAVE_1002
{
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Actual_Position;                // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Position (Offset: 26.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Actual_Velocity;                // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Velocity (Offset: 30.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Absolute_Position;              // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Absolute Position (Offset: 34.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Rotor_Absolute_Position;        // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Rotor Absolute Position (Offset: 38.0, Size: 4.0, Datatype: DINT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Inputs_Actual_Torque;                   // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Torque (Offset: 42.0, Size: 2.0, Datatype: INT)
  EC_T_WORD   wModule_1_csv_csp__axis_Inputs_Status_Word;                      // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Status Word (Offset: 44.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wModule_1_csv_csp__axis_Inputs_Error_Code;                       // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Error Code (Offset: 46.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Inputs_Mode_of_Operation_Display;       // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Mode of Operation Display (Offset: 48.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Inputs_Torque_Sensor;                   // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Torque Sensor (Offset: 50.0, Size: 2.0, Datatype: INT)
} EC_PACKED(1) T_PDLAYOUT_IN_SLAVE_1002;
#include EC_PACKED_INCLUDESTOP

#include EC_PACKED_INCLUDESTART(1)
#define PDLAYOUT_IN_OFFSET_SLAVE_1003 52
typedef struct _T_PDLAYOUT_IN_SLAVE_1003
{
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Actual_Position;                // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Position (Offset: 52.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Actual_Velocity;                // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Velocity (Offset: 56.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Absolute_Position;              // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Absolute Position (Offset: 60.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Rotor_Absolute_Position;        // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Rotor Absolute Position (Offset: 64.0, Size: 4.0, Datatype: DINT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Inputs_Actual_Torque;                   // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Torque (Offset: 68.0, Size: 2.0, Datatype: INT)
  EC_T_WORD   wModule_1_csv_csp__axis_Inputs_Status_Word;                      // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Status Word (Offset: 70.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wModule_1_csv_csp__axis_Inputs_Error_Code;                       // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Error Code (Offset: 72.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Inputs_Mode_of_Operation_Display;       // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Mode of Operation Display (Offset: 74.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Inputs_Torque_Sensor;                   // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Torque Sensor (Offset: 76.0, Size: 2.0, Datatype: INT)
} EC_PACKED(1) T_PDLAYOUT_IN_SLAVE_1003;
#include EC_PACKED_INCLUDESTOP

#include EC_PACKED_INCLUDESTART(1)
#define PDLAYOUT_IN_OFFSET_SLAVE_1004 78
typedef struct _T_PDLAYOUT_IN_SLAVE_1004
{
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Actual_Position;                // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Position (Offset: 78.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Actual_Velocity;                // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Velocity (Offset: 82.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Absolute_Position;              // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Absolute Position (Offset: 86.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Rotor_Absolute_Position;        // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Rotor Absolute Position (Offset: 90.0, Size: 4.0, Datatype: DINT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Inputs_Actual_Torque;                   // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Torque (Offset: 94.0, Size: 2.0, Datatype: INT)
  EC_T_WORD   wModule_1_csv_csp__axis_Inputs_Status_Word;                      // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Status Word (Offset: 96.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wModule_1_csv_csp__axis_Inputs_Error_Code;                       // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Error Code (Offset: 98.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Inputs_Mode_of_Operation_Display;       // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Mode of Operation Display (Offset: 100.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Inputs_Torque_Sensor;                   // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Torque Sensor (Offset: 102.0, Size: 2.0, Datatype: INT)
} EC_PACKED(1) T_PDLAYOUT_IN_SLAVE_1004;
#include EC_PACKED_INCLUDESTOP

#include EC_PACKED_INCLUDESTART(1)
#define PDLAYOUT_IN_OFFSET_SLAVE_1005 104
typedef struct _T_PDLAYOUT_IN_SLAVE_1005
{
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Actual_Position;                // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Position (Offset: 104.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Actual_Velocity;                // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Velocity (Offset: 108.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Absolute_Position;              // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Absolute Position (Offset: 112.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Rotor_Absolute_Position;        // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Rotor Absolute Position (Offset: 116.0, Size: 4.0, Datatype: DINT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Inputs_Actual_Torque;                   // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Torque (Offset: 120.0, Size: 2.0, Datatype: INT)
  EC_T_WORD   wModule_1_csv_csp__axis_Inputs_Status_Word;                      // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Status Word (Offset: 122.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wModule_1_csv_csp__axis_Inputs_Error_Code;                       // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Error Code (Offset: 124.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Inputs_Mode_of_Operation_Display;       // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Mode of Operation Display (Offset: 126.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Inputs_Torque_Sensor;                   // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Torque Sensor (Offset: 128.0, Size: 2.0, Datatype: INT)
} EC_PACKED(1) T_PDLAYOUT_IN_SLAVE_1005;
#include EC_PACKED_INCLUDESTOP

#include EC_PACKED_INCLUDESTART(1)
#define PDLAYOUT_IN_OFFSET_SLAVE_1006 130
typedef struct _T_PDLAYOUT_IN_SLAVE_1006
{
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Actual_Position;                // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Position (Offset: 130.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Actual_Velocity;                // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Velocity (Offset: 134.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Absolute_Position;              // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Absolute Position (Offset: 138.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Inputs_Rotor_Absolute_Position;        // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Rotor Absolute Position (Offset: 142.0, Size: 4.0, Datatype: DINT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Inputs_Actual_Torque;                   // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Torque (Offset: 146.0, Size: 2.0, Datatype: INT)
  EC_T_WORD   wModule_1_csv_csp__axis_Inputs_Status_Word;                      // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Status Word (Offset: 148.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wModule_1_csv_csp__axis_Inputs_Error_Code;                       // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Error Code (Offset: 150.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Inputs_Mode_of_Operation_Display;       // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Mode of Operation Display (Offset: 152.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Inputs_Torque_Sensor;                   // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Torque Sensor (Offset: 154.0, Size: 2.0, Datatype: INT)
} EC_PACKED(1) T_PDLAYOUT_IN_SLAVE_1006;
#include EC_PACKED_INCLUDESTOP

#include EC_PACKED_INCLUDESTART(1)
#define PDLAYOUT_IN_OFFSET_SLAVE_1007 156
typedef struct _T_PDLAYOUT_IN_SLAVE_1007
{
  EC_T_WORD   wTxPDO_2_Communication_Status;                                   // Slave_1007 [KR_LED].TxPDO 2.Communication_Status (Offset: 156.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wTxPDO_2_Gripper_Status;                                         // Slave_1007 [KR_LED].TxPDO 2.Gripper_Status (Offset: 158.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wTxPDO_2_Motor_Abs_Pos;                                          // Slave_1007 [KR_LED].TxPDO 2.Motor_Abs_Pos (Offset: 160.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wTxPDO_2_Actual_current;                                         // Slave_1007 [KR_LED].TxPDO 2.Actual_current (Offset: 162.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wTxPDO_2_Motor_Vel;                                              // Slave_1007 [KR_LED].TxPDO 2.Motor_Vel (Offset: 164.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wTxPDO_2_Gripper_Pos;                                            // Slave_1007 [KR_LED].TxPDO 2.Gripper_Pos (Offset: 166.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wTxPDO_2_Bus_Voltage;                                            // Slave_1007 [KR_LED].TxPDO 2.Bus_Voltage (Offset: 168.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wTxPDO_2_Btn_Status;                                             // Slave_1007 [KR_LED].TxPDO 2.Btn_Status (Offset: 170.0, Size: 2.0, Datatype: UINT)
} EC_PACKED(1) T_PDLAYOUT_IN_SLAVE_1007;
#include EC_PACKED_INCLUDESTOP

/*-OUTPUT SLAVES-------------------------------------------------------------*/

#include EC_PACKED_INCLUDESTART(1)
#define PDLAYOUT_OUT_OFFSET_SLAVE_1001 0
typedef struct _T_PDLAYOUT_OUT_SLAVE_1001
{
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Outputs_Target_Position;               // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Position (Offset: 0.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Outputs_Target_Velocity;               // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Velocity (Offset: 4.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Outputs_Acceleration_Feedforward;      // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Acceleration Feedforward (Offset: 8.0, Size: 4.0, Datatype: DINT)
  EC_T_WORD   wModule_1_csv_csp__axis_Outputs_Control_Word;                    // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Control Word (Offset: 12.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_Target_Torque;                  // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Torque (Offset: 14.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_Inertia;                        // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Inertia (Offset: 16.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_Mode_of_Operation;              // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Mode of Operation (Offset: 18.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_EEPROM_data;                    // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.EEPROM data (Offset: 20.0, Size: 2.0, Datatype: INT)
} EC_PACKED(1) T_PDLAYOUT_OUT_SLAVE_1001;
#include EC_PACKED_INCLUDESTOP

#include EC_PACKED_INCLUDESTART(1)
#define PDLAYOUT_OUT_OFFSET_SLAVE_1002 26
typedef struct _T_PDLAYOUT_OUT_SLAVE_1002
{
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Outputs_Target_Position;               // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Position (Offset: 26.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Outputs_Target_Velocity;               // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Velocity (Offset: 30.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Outputs_Acceleration_Feedforward;      // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Acceleration Feedforward (Offset: 34.0, Size: 4.0, Datatype: DINT)
  EC_T_WORD   wModule_1_csv_csp__axis_Outputs_Control_Word;                    // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Control Word (Offset: 38.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_Target_Torque;                  // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Torque (Offset: 40.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_Inertia;                        // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Inertia (Offset: 42.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_Mode_of_Operation;              // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Mode of Operation (Offset: 44.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_EEPROM_data;                    // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.EEPROM data (Offset: 46.0, Size: 2.0, Datatype: INT)
} EC_PACKED(1) T_PDLAYOUT_OUT_SLAVE_1002;
#include EC_PACKED_INCLUDESTOP

#include EC_PACKED_INCLUDESTART(1)
#define PDLAYOUT_OUT_OFFSET_SLAVE_1003 52
typedef struct _T_PDLAYOUT_OUT_SLAVE_1003
{
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Outputs_Target_Position;               // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Position (Offset: 52.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Outputs_Target_Velocity;               // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Velocity (Offset: 56.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Outputs_Acceleration_Feedforward;      // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Acceleration Feedforward (Offset: 60.0, Size: 4.0, Datatype: DINT)
  EC_T_WORD   wModule_1_csv_csp__axis_Outputs_Control_Word;                    // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Control Word (Offset: 64.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_Target_Torque;                  // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Torque (Offset: 66.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_Inertia;                        // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Inertia (Offset: 68.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_Mode_of_Operation;              // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Mode of Operation (Offset: 70.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_EEPROM_data;                    // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.EEPROM data (Offset: 72.0, Size: 2.0, Datatype: INT)
} EC_PACKED(1) T_PDLAYOUT_OUT_SLAVE_1003;
#include EC_PACKED_INCLUDESTOP

#include EC_PACKED_INCLUDESTART(1)
#define PDLAYOUT_OUT_OFFSET_SLAVE_1004 78
typedef struct _T_PDLAYOUT_OUT_SLAVE_1004
{
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Outputs_Target_Position;               // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Position (Offset: 78.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Outputs_Target_Velocity;               // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Velocity (Offset: 82.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Outputs_Acceleration_Feedforward;      // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Acceleration Feedforward (Offset: 86.0, Size: 4.0, Datatype: DINT)
  EC_T_WORD   wModule_1_csv_csp__axis_Outputs_Control_Word;                    // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Control Word (Offset: 90.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_Target_Torque;                  // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Torque (Offset: 92.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_Inertia;                        // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Inertia (Offset: 94.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_Mode_of_Operation;              // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Mode of Operation (Offset: 96.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_EEPROM_data;                    // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.EEPROM data (Offset: 98.0, Size: 2.0, Datatype: INT)
} EC_PACKED(1) T_PDLAYOUT_OUT_SLAVE_1004;
#include EC_PACKED_INCLUDESTOP

#include EC_PACKED_INCLUDESTART(1)
#define PDLAYOUT_OUT_OFFSET_SLAVE_1005 104
typedef struct _T_PDLAYOUT_OUT_SLAVE_1005
{
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Outputs_Target_Position;               // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Position (Offset: 104.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Outputs_Target_Velocity;               // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Velocity (Offset: 108.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Outputs_Acceleration_Feedforward;      // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Acceleration Feedforward (Offset: 112.0, Size: 4.0, Datatype: DINT)
  EC_T_WORD   wModule_1_csv_csp__axis_Outputs_Control_Word;                    // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Control Word (Offset: 116.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_Target_Torque;                  // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Torque (Offset: 118.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_Inertia;                        // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Inertia (Offset: 120.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_Mode_of_Operation;              // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Mode of Operation (Offset: 122.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_EEPROM_data;                    // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.EEPROM data (Offset: 124.0, Size: 2.0, Datatype: INT)
} EC_PACKED(1) T_PDLAYOUT_OUT_SLAVE_1005;
#include EC_PACKED_INCLUDESTOP

#include EC_PACKED_INCLUDESTART(1)
#define PDLAYOUT_OUT_OFFSET_SLAVE_1006 130
typedef struct _T_PDLAYOUT_OUT_SLAVE_1006
{
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Outputs_Target_Position;               // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Position (Offset: 130.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Outputs_Target_Velocity;               // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Velocity (Offset: 134.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwModule_1_csv_csp__axis_Outputs_Acceleration_Feedforward;      // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Acceleration Feedforward (Offset: 138.0, Size: 4.0, Datatype: DINT)
  EC_T_WORD   wModule_1_csv_csp__axis_Outputs_Control_Word;                    // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Control Word (Offset: 142.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_Target_Torque;                  // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Torque (Offset: 144.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_Inertia;                        // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Inertia (Offset: 146.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_Mode_of_Operation;              // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Mode of Operation (Offset: 148.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swModule_1_csv_csp__axis_Outputs_EEPROM_data;                    // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.EEPROM data (Offset: 150.0, Size: 2.0, Datatype: INT)
} EC_PACKED(1) T_PDLAYOUT_OUT_SLAVE_1006;
#include EC_PACKED_INCLUDESTOP

#include EC_PACKED_INCLUDESTART(1)
#define PDLAYOUT_OUT_OFFSET_SLAVE_1007 156
typedef struct _T_PDLAYOUT_OUT_SLAVE_1007
{
  EC_T_WORD   wOutputs_LED_Color;                                              // Slave_1007 [KR_LED].Outputs.LED_Color (Offset: 156.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wOutputs_LED_Switching;                                          // Slave_1007 [KR_LED].Outputs.LED_Switching (Offset: 158.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wOutputs_Digital_Output;                                         // Slave_1007 [KR_LED].Outputs.Digital_Output (Offset: 160.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wOutputs_Control_Word;                                           // Slave_1007 [KR_LED].Outputs.Control_Word (Offset: 162.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wOutputs_Gripper_Command;                                        // Slave_1007 [KR_LED].Outputs.Gripper_Command (Offset: 164.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wOutputs_Gripper_Value;                                          // Slave_1007 [KR_LED].Outputs.Gripper_Value (Offset: 166.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wOutputs_Para_Control__7_Data_Value;                             // Slave_1007 [KR_LED].Outputs.Para Control - 7 Data Value (Offset: 168.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wOutputs_Para_Control__8_Data_Value;                             // Slave_1007 [KR_LED].Outputs.Para Control - 8 Data Value (Offset: 170.0, Size: 2.0, Datatype: UINT)
} EC_PACKED(1) T_PDLAYOUT_OUT_SLAVE_1007;
#include EC_PACKED_INCLUDESTOP

/*-INPUT PD LAYOUT-----------------------------------------------------------*/

#include EC_PACKED_INCLUDESTART(1)
typedef struct _T_PDLAYOUT_IN
{
  EC_T_SDWORD sdwSlave_1001_Module_1_csv_csp__axis_Inputs_Actual_Position;     // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Position (Offset: 0.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1001_Module_1_csv_csp__axis_Inputs_Actual_Velocity;     // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Velocity (Offset: 4.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1001_Module_1_csv_csp__axis_Inputs_Absolute_Position;   // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Absolute Position (Offset: 8.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1001_Module_1_csv_csp__axis_Inputs_Rotor_Absolute_Position; // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Rotor Absolute Position (Offset: 12.0, Size: 4.0, Datatype: DINT)
  EC_T_SWORD  swSlave_1001_Module_1_csv_csp__axis_Inputs_Actual_Torque;        // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Torque (Offset: 16.0, Size: 2.0, Datatype: INT)
  EC_T_WORD   wSlave_1001_Module_1_csv_csp__axis_Inputs_Status_Word;           // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Status Word (Offset: 18.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wSlave_1001_Module_1_csv_csp__axis_Inputs_Error_Code;            // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Error Code (Offset: 20.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swSlave_1001_Module_1_csv_csp__axis_Inputs_Mode_of_Operation_Display; // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Mode of Operation Display (Offset: 22.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1001_Module_1_csv_csp__axis_Inputs_Torque_Sensor;        // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Torque Sensor (Offset: 24.0, Size: 2.0, Datatype: INT)
  EC_T_SDWORD sdwSlave_1002_Module_1_csv_csp__axis_Inputs_Actual_Position;     // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Position (Offset: 26.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1002_Module_1_csv_csp__axis_Inputs_Actual_Velocity;     // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Velocity (Offset: 30.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1002_Module_1_csv_csp__axis_Inputs_Absolute_Position;   // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Absolute Position (Offset: 34.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1002_Module_1_csv_csp__axis_Inputs_Rotor_Absolute_Position; // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Rotor Absolute Position (Offset: 38.0, Size: 4.0, Datatype: DINT)
  EC_T_SWORD  swSlave_1002_Module_1_csv_csp__axis_Inputs_Actual_Torque;        // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Torque (Offset: 42.0, Size: 2.0, Datatype: INT)
  EC_T_WORD   wSlave_1002_Module_1_csv_csp__axis_Inputs_Status_Word;           // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Status Word (Offset: 44.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wSlave_1002_Module_1_csv_csp__axis_Inputs_Error_Code;            // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Error Code (Offset: 46.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swSlave_1002_Module_1_csv_csp__axis_Inputs_Mode_of_Operation_Display; // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Mode of Operation Display (Offset: 48.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1002_Module_1_csv_csp__axis_Inputs_Torque_Sensor;        // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Torque Sensor (Offset: 50.0, Size: 2.0, Datatype: INT)
  EC_T_SDWORD sdwSlave_1003_Module_1_csv_csp__axis_Inputs_Actual_Position;     // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Position (Offset: 52.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1003_Module_1_csv_csp__axis_Inputs_Actual_Velocity;     // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Velocity (Offset: 56.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1003_Module_1_csv_csp__axis_Inputs_Absolute_Position;   // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Absolute Position (Offset: 60.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1003_Module_1_csv_csp__axis_Inputs_Rotor_Absolute_Position; // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Rotor Absolute Position (Offset: 64.0, Size: 4.0, Datatype: DINT)
  EC_T_SWORD  swSlave_1003_Module_1_csv_csp__axis_Inputs_Actual_Torque;        // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Torque (Offset: 68.0, Size: 2.0, Datatype: INT)
  EC_T_WORD   wSlave_1003_Module_1_csv_csp__axis_Inputs_Status_Word;           // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Status Word (Offset: 70.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wSlave_1003_Module_1_csv_csp__axis_Inputs_Error_Code;            // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Error Code (Offset: 72.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swSlave_1003_Module_1_csv_csp__axis_Inputs_Mode_of_Operation_Display; // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Mode of Operation Display (Offset: 74.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1003_Module_1_csv_csp__axis_Inputs_Torque_Sensor;        // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Torque Sensor (Offset: 76.0, Size: 2.0, Datatype: INT)
  EC_T_SDWORD sdwSlave_1004_Module_1_csv_csp__axis_Inputs_Actual_Position;     // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Position (Offset: 78.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1004_Module_1_csv_csp__axis_Inputs_Actual_Velocity;     // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Velocity (Offset: 82.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1004_Module_1_csv_csp__axis_Inputs_Absolute_Position;   // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Absolute Position (Offset: 86.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1004_Module_1_csv_csp__axis_Inputs_Rotor_Absolute_Position; // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Rotor Absolute Position (Offset: 90.0, Size: 4.0, Datatype: DINT)
  EC_T_SWORD  swSlave_1004_Module_1_csv_csp__axis_Inputs_Actual_Torque;        // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Torque (Offset: 94.0, Size: 2.0, Datatype: INT)
  EC_T_WORD   wSlave_1004_Module_1_csv_csp__axis_Inputs_Status_Word;           // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Status Word (Offset: 96.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wSlave_1004_Module_1_csv_csp__axis_Inputs_Error_Code;            // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Error Code (Offset: 98.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swSlave_1004_Module_1_csv_csp__axis_Inputs_Mode_of_Operation_Display; // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Mode of Operation Display (Offset: 100.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1004_Module_1_csv_csp__axis_Inputs_Torque_Sensor;        // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Torque Sensor (Offset: 102.0, Size: 2.0, Datatype: INT)
  EC_T_SDWORD sdwSlave_1005_Module_1_csv_csp__axis_Inputs_Actual_Position;     // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Position (Offset: 104.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1005_Module_1_csv_csp__axis_Inputs_Actual_Velocity;     // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Velocity (Offset: 108.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1005_Module_1_csv_csp__axis_Inputs_Absolute_Position;   // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Absolute Position (Offset: 112.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1005_Module_1_csv_csp__axis_Inputs_Rotor_Absolute_Position; // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Rotor Absolute Position (Offset: 116.0, Size: 4.0, Datatype: DINT)
  EC_T_SWORD  swSlave_1005_Module_1_csv_csp__axis_Inputs_Actual_Torque;        // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Torque (Offset: 120.0, Size: 2.0, Datatype: INT)
  EC_T_WORD   wSlave_1005_Module_1_csv_csp__axis_Inputs_Status_Word;           // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Status Word (Offset: 122.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wSlave_1005_Module_1_csv_csp__axis_Inputs_Error_Code;            // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Error Code (Offset: 124.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swSlave_1005_Module_1_csv_csp__axis_Inputs_Mode_of_Operation_Display; // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Mode of Operation Display (Offset: 126.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1005_Module_1_csv_csp__axis_Inputs_Torque_Sensor;        // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Torque Sensor (Offset: 128.0, Size: 2.0, Datatype: INT)
  EC_T_SDWORD sdwSlave_1006_Module_1_csv_csp__axis_Inputs_Actual_Position;     // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Position (Offset: 130.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1006_Module_1_csv_csp__axis_Inputs_Actual_Velocity;     // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Velocity (Offset: 134.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1006_Module_1_csv_csp__axis_Inputs_Absolute_Position;   // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Absolute Position (Offset: 138.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1006_Module_1_csv_csp__axis_Inputs_Rotor_Absolute_Position; // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Rotor Absolute Position (Offset: 142.0, Size: 4.0, Datatype: DINT)
  EC_T_SWORD  swSlave_1006_Module_1_csv_csp__axis_Inputs_Actual_Torque;        // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Actual Torque (Offset: 146.0, Size: 2.0, Datatype: INT)
  EC_T_WORD   wSlave_1006_Module_1_csv_csp__axis_Inputs_Status_Word;           // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Status Word (Offset: 148.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wSlave_1006_Module_1_csv_csp__axis_Inputs_Error_Code;            // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Error Code (Offset: 150.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swSlave_1006_Module_1_csv_csp__axis_Inputs_Mode_of_Operation_Display; // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Mode of Operation Display (Offset: 152.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1006_Module_1_csv_csp__axis_Inputs_Torque_Sensor;        // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Inputs.Torque Sensor (Offset: 154.0, Size: 2.0, Datatype: INT)
  EC_T_WORD   wSlave_1007_TxPDO_2_Communication_Status;                        // Slave_1007 [KR_LED].TxPDO 2.Communication_Status (Offset: 156.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wSlave_1007_TxPDO_2_Gripper_Status;                              // Slave_1007 [KR_LED].TxPDO 2.Gripper_Status (Offset: 158.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wSlave_1007_TxPDO_2_Motor_Abs_Pos;                               // Slave_1007 [KR_LED].TxPDO 2.Motor_Abs_Pos (Offset: 160.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wSlave_1007_TxPDO_2_Actual_current;                              // Slave_1007 [KR_LED].TxPDO 2.Actual_current (Offset: 162.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wSlave_1007_TxPDO_2_Motor_Vel;                                   // Slave_1007 [KR_LED].TxPDO 2.Motor_Vel (Offset: 164.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wSlave_1007_TxPDO_2_Gripper_Pos;                                 // Slave_1007 [KR_LED].TxPDO 2.Gripper_Pos (Offset: 166.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wSlave_1007_TxPDO_2_Bus_Voltage;                                 // Slave_1007 [KR_LED].TxPDO 2.Bus_Voltage (Offset: 168.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wSlave_1007_TxPDO_2_Btn_Status;                                  // Slave_1007 [KR_LED].TxPDO 2.Btn_Status (Offset: 170.0, Size: 2.0, Datatype: UINT)
} EC_PACKED(1) T_PDLAYOUT_IN;
#include EC_PACKED_INCLUDESTOP

/*-OUTPUT PD LAYOUT----------------------------------------------------------*/

#include EC_PACKED_INCLUDESTART(1)
typedef struct _T_PDLAYOUT_OUT
{
  EC_T_SDWORD sdwSlave_1001_Module_1_csv_csp__axis_Outputs_Target_Position;    // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Position (Offset: 0.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1001_Module_1_csv_csp__axis_Outputs_Target_Velocity;    // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Velocity (Offset: 4.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1001_Module_1_csv_csp__axis_Outputs_Acceleration_Feedforward; // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Acceleration Feedforward (Offset: 8.0, Size: 4.0, Datatype: DINT)
  EC_T_WORD   wSlave_1001_Module_1_csv_csp__axis_Outputs_Control_Word;         // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Control Word (Offset: 12.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swSlave_1001_Module_1_csv_csp__axis_Outputs_Target_Torque;       // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Torque (Offset: 14.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1001_Module_1_csv_csp__axis_Outputs_Inertia;             // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Inertia (Offset: 16.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1001_Module_1_csv_csp__axis_Outputs_Mode_of_Operation;   // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Mode of Operation (Offset: 18.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1001_Module_1_csv_csp__axis_Outputs_EEPROM_data;         // Slave_1001 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.EEPROM data (Offset: 20.0, Size: 2.0, Datatype: INT)
  EC_T_BYTE   byReserved0[4];                                                  // Reserved bytes
  EC_T_SDWORD sdwSlave_1002_Module_1_csv_csp__axis_Outputs_Target_Position;    // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Position (Offset: 26.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1002_Module_1_csv_csp__axis_Outputs_Target_Velocity;    // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Velocity (Offset: 30.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1002_Module_1_csv_csp__axis_Outputs_Acceleration_Feedforward; // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Acceleration Feedforward (Offset: 34.0, Size: 4.0, Datatype: DINT)
  EC_T_WORD   wSlave_1002_Module_1_csv_csp__axis_Outputs_Control_Word;         // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Control Word (Offset: 38.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swSlave_1002_Module_1_csv_csp__axis_Outputs_Target_Torque;       // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Torque (Offset: 40.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1002_Module_1_csv_csp__axis_Outputs_Inertia;             // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Inertia (Offset: 42.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1002_Module_1_csv_csp__axis_Outputs_Mode_of_Operation;   // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Mode of Operation (Offset: 44.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1002_Module_1_csv_csp__axis_Outputs_EEPROM_data;         // Slave_1002 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.EEPROM data (Offset: 46.0, Size: 2.0, Datatype: INT)
  EC_T_BYTE   byReserved1[4];                                                  // Reserved bytes
  EC_T_SDWORD sdwSlave_1003_Module_1_csv_csp__axis_Outputs_Target_Position;    // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Position (Offset: 52.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1003_Module_1_csv_csp__axis_Outputs_Target_Velocity;    // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Velocity (Offset: 56.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1003_Module_1_csv_csp__axis_Outputs_Acceleration_Feedforward; // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Acceleration Feedforward (Offset: 60.0, Size: 4.0, Datatype: DINT)
  EC_T_WORD   wSlave_1003_Module_1_csv_csp__axis_Outputs_Control_Word;         // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Control Word (Offset: 64.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swSlave_1003_Module_1_csv_csp__axis_Outputs_Target_Torque;       // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Torque (Offset: 66.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1003_Module_1_csv_csp__axis_Outputs_Inertia;             // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Inertia (Offset: 68.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1003_Module_1_csv_csp__axis_Outputs_Mode_of_Operation;   // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Mode of Operation (Offset: 70.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1003_Module_1_csv_csp__axis_Outputs_EEPROM_data;         // Slave_1003 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.EEPROM data (Offset: 72.0, Size: 2.0, Datatype: INT)
  EC_T_BYTE   byReserved2[4];                                                  // Reserved bytes
  EC_T_SDWORD sdwSlave_1004_Module_1_csv_csp__axis_Outputs_Target_Position;    // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Position (Offset: 78.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1004_Module_1_csv_csp__axis_Outputs_Target_Velocity;    // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Velocity (Offset: 82.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1004_Module_1_csv_csp__axis_Outputs_Acceleration_Feedforward; // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Acceleration Feedforward (Offset: 86.0, Size: 4.0, Datatype: DINT)
  EC_T_WORD   wSlave_1004_Module_1_csv_csp__axis_Outputs_Control_Word;         // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Control Word (Offset: 90.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swSlave_1004_Module_1_csv_csp__axis_Outputs_Target_Torque;       // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Torque (Offset: 92.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1004_Module_1_csv_csp__axis_Outputs_Inertia;             // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Inertia (Offset: 94.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1004_Module_1_csv_csp__axis_Outputs_Mode_of_Operation;   // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Mode of Operation (Offset: 96.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1004_Module_1_csv_csp__axis_Outputs_EEPROM_data;         // Slave_1004 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.EEPROM data (Offset: 98.0, Size: 2.0, Datatype: INT)
  EC_T_BYTE   byReserved3[4];                                                  // Reserved bytes
  EC_T_SDWORD sdwSlave_1005_Module_1_csv_csp__axis_Outputs_Target_Position;    // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Position (Offset: 104.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1005_Module_1_csv_csp__axis_Outputs_Target_Velocity;    // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Velocity (Offset: 108.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1005_Module_1_csv_csp__axis_Outputs_Acceleration_Feedforward; // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Acceleration Feedforward (Offset: 112.0, Size: 4.0, Datatype: DINT)
  EC_T_WORD   wSlave_1005_Module_1_csv_csp__axis_Outputs_Control_Word;         // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Control Word (Offset: 116.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swSlave_1005_Module_1_csv_csp__axis_Outputs_Target_Torque;       // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Torque (Offset: 118.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1005_Module_1_csv_csp__axis_Outputs_Inertia;             // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Inertia (Offset: 120.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1005_Module_1_csv_csp__axis_Outputs_Mode_of_Operation;   // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Mode of Operation (Offset: 122.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1005_Module_1_csv_csp__axis_Outputs_EEPROM_data;         // Slave_1005 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.EEPROM data (Offset: 124.0, Size: 2.0, Datatype: INT)
  EC_T_BYTE   byReserved4[4];                                                  // Reserved bytes
  EC_T_SDWORD sdwSlave_1006_Module_1_csv_csp__axis_Outputs_Target_Position;    // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Position (Offset: 130.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1006_Module_1_csv_csp__axis_Outputs_Target_Velocity;    // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Velocity (Offset: 134.0, Size: 4.0, Datatype: DINT)
  EC_T_SDWORD sdwSlave_1006_Module_1_csv_csp__axis_Outputs_Acceleration_Feedforward; // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Acceleration Feedforward (Offset: 138.0, Size: 4.0, Datatype: DINT)
  EC_T_WORD   wSlave_1006_Module_1_csv_csp__axis_Outputs_Control_Word;         // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Control Word (Offset: 142.0, Size: 2.0, Datatype: UINT)
  EC_T_SWORD  swSlave_1006_Module_1_csv_csp__axis_Outputs_Target_Torque;       // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Target Torque (Offset: 144.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1006_Module_1_csv_csp__axis_Outputs_Inertia;             // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Inertia (Offset: 146.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1006_Module_1_csv_csp__axis_Outputs_Mode_of_Operation;   // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.Mode of Operation (Offset: 148.0, Size: 2.0, Datatype: INT)
  EC_T_SWORD  swSlave_1006_Module_1_csv_csp__axis_Outputs_EEPROM_data;         // Slave_1006 [KUEMD_revD].Module 1 (csv,csp - axis).Outputs.EEPROM data (Offset: 150.0, Size: 2.0, Datatype: INT)
  EC_T_BYTE   byReserved5[4];                                                  // Reserved bytes
  EC_T_WORD   wSlave_1007_Outputs_LED_Color;                                   // Slave_1007 [KR_LED].Outputs.LED_Color (Offset: 156.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wSlave_1007_Outputs_LED_Switching;                               // Slave_1007 [KR_LED].Outputs.LED_Switching (Offset: 158.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wSlave_1007_Outputs_Digital_Output;                              // Slave_1007 [KR_LED].Outputs.Digital_Output (Offset: 160.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wSlave_1007_Outputs_Control_Word;                                // Slave_1007 [KR_LED].Outputs.Control_Word (Offset: 162.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wSlave_1007_Outputs_Gripper_Command;                             // Slave_1007 [KR_LED].Outputs.Gripper_Command (Offset: 164.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wSlave_1007_Outputs_Gripper_Value;                               // Slave_1007 [KR_LED].Outputs.Gripper_Value (Offset: 166.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wSlave_1007_Outputs_Para_Control__7_Data_Value;                  // Slave_1007 [KR_LED].Outputs.Para Control - 7 Data Value (Offset: 168.0, Size: 2.0, Datatype: UINT)
  EC_T_WORD   wSlave_1007_Outputs_Para_Control__8_Data_Value;                  // Slave_1007 [KR_LED].Outputs.Para Control - 8 Data Value (Offset: 170.0, Size: 2.0, Datatype: UINT)
} EC_PACKED(1) T_PDLAYOUT_OUT;
#include EC_PACKED_INCLUDESTOP

#endif
