bool do_matching
bool do_scan_sampling
int32 robot_id
int32 target_id
string target_name
int32 sampling_num
int32 feature_ext_method
float64 voxel_downsampling_size

int32 segmentation_method
int32 rgs_normal_k
int32 rgs_min_size
int32 rgs_max_size
float64 rgs_thre_angle
float64 rgs_thre_curvature
int32 rgs_neighbor_k

float64 color_rgs_neighbor_r
float64 color_rgs_thre_1st_color
float64 color_rgs_thre_2nd_color
int32 color_rgs_min_cluster_size
float64 color_rgs_neighbor_r_2
float64 color_rgs_thre_1st_color_2
float64 color_rgs_thre_2nd_color_2
int32 color_rgs_min_cluster_size_2

float64 euclidean_cluster_tol
int32 euclidean_min_cluster_size
int32 euclidean_max_cluster_size


---
float64[] pose
float64[] sub_pose
float64[] zig_pose
float64 grp_width
float64 approach_distance
bool is_pose
float64 matching_accuracy
